### ISSUE TITLE
Add related resources component to Docs Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1353]
As a follow up on #427 we want to now enable the right rail component to return related resource content links. In order to this we need to clarify some questions around cost and how we'll need to implement the refresh rate of content per page.

### Considerations

- We refetch results per page once a day on a cron job. The data is available as [part of the build: ](https://github.com/newrelic/developer-website/blob/develop/src/data/related-pages.json)
- That data gets rebuilt [in this action once]( https://github.com/newrelic/developer-website/blob/develop/.github/workflows/fetch-related-content.yml) a day:
- We can specify whatever interval we want if we go this route. When we execute a query per page each time we fetch related content for a page. We have a limit on the number of queries we can run before we are charged more. We could decrease the interval and instead do once a week, or once a month.  Doing so would put costs down, but means that auto related content could become stale (maybe thats a fair tradeoff)

### Acceptance Criteria

- [x] confirm who will be paying for the additional costs to run the swiftype queries. - `APPROVED`  it's all in Slack. in #swiftype-devs 👍 

### Cost
```
estimated cost: about 60k searches/month (assuming 2k searches * 30 days), just to populate the 
links for Related Content between $400 - $600 a month in swiftype 
cost. This is based on our current pricing plan

```

### Interval
```
To cap it at 60k queries a month, that means we can do 2K a day max...since there's a query per page and we have 5kish pages,  we would want to run this job once every 3 days (72 hrs) as the most frequent interval we could do 
```

- [x] Finish the Implementation of the right rail component on the docs site and generate related content links into pages. We are approved to do `60k searches/month (assuming 2k searches * 30 days)

> NOTE: JV tested this out in #1356 so it seems to be working with static resource links in frontmatter.

- [ ] [Update the Style Guide](https://docs.newrelic.com/docs/style-guide/) to ensure we define how this feature works. we can pass this off to a Docs Writer, so let's create a content ticket and have @paperclypse review it.

- [x]  There is a small bug when running the build for related resources which is why there are no pages with it currently. Right now you can run the build for related resources on demand, which will query Swiftype for all pages, but last I [ran this](https://github.com/newrelic/docs-website/actions/runs/604770713) it failed due to an error from the Swiftype API that we did not catch properly.

### Mock Up

<img width="417" alt="Screen Shot 2021-03-16 at 3 15 21 PM" src="https://user-images.githubusercontent.com/1395158/111380837-7d31c080-866a-11eb-885b-fca38ba56b92.png">

**Comment by jerelmiller** [comment]
@jpvajda Technically this is implemented, but there is a small bug when running the build for related resources which is why there are no pages with it currently. Right now you can run the build for related resources on demand, which will query Swiftype for all pages, but [last I ran this](https://github.com/newrelic/docs-website/actions/runs/604770713) it failed due to an error from the Swiftype API that we did not catch properly.

**Comment by jpvajda** [comment]
@jerelmiller Thank you! I added this info to the AC.
