### ISSUE TITLE
Create a private repo in New Relic Org

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1685]
## Description
In order to support editing multiple docs, updating the nav, with multiple contributors (#1063), we have decided we would like a private fork of this repository in our Github environment.

This ticket _does not_ include the work to keep the private repository in sync with the public one.

## Acceptance Criteria
* [x] Private repository created in Github
* [x] Content from the public repository pushed to the private repository
* [x] New project created in Amplify and connected to the private repository
* [x] Amplify environment password protected
* [x] DevEn team and docs writer team able to contribute to the new private repository

**Comment by nr-kkenney** [comment]
updated the ticket to reflect that i think we can just use public github for this.

**Comment by nr-kkenney** [comment]
for the action's implementation, i think we only need to sync develop & main (versus every single branch), since those are the long living branches from the public repo.

i also think the action can just merge the remote branches & push that up directly. this should always be fast forward merge w/ no conflicts, since no one should push to develop / main within this repo.

if we want to push for some standardized naming of branches, we might also be able to automatically sync the branches writers are working on (with changes from public develop, etc), but I think this is a stretch goal.

**Comment by nr-kkenney** [comment]
zack's doc: https://docs.google.com/document/d/1Lk16HGkWHlf52icq8AmaAiUp-lzFHEULCP7RAVjJ4aY/edit

**Comment by nr-kkenney** [comment]
submitted a ticket for the creation of the repo: https://newrelic.atlassian.net/browse/OSSREQ-225

**Comment by paperclypse** [comment]
Once you have this private repo in place, I have a good candidate for trying it out.

**Comment by LizBaker** [comment]
in the home stretch but haven't gotten a successful build on amplify yet

**Comment by LizBaker** [comment]
success! adding the `--max-old-space-size` flag to the env variables along with a couple others seemed to sort things out. just performing some final clean up before closing

**Comment by nr-kkenney** [comment]
@paperclypse forgot to mention this should be good to go. if yall can capture feedback somewhere, that would be 👍
